name: CI

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download
        run: |
          sudo apt update
          sudo apt install aria2 python3 -y
          python3 ./generate_download_list.py
          aria2c --dir=./downloads --continue=true --input-file=./aria2c_input.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            downloads/*
          release_name: Downloads

